name: Build and Validate

on: [push]

jobs:
  build_core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew bootRun &

      - name: Wait for service
        run: curl --retry-max-time 60 --retry 100 --retry-delay 1 --retry-connrefused -fail http://localhost:8080/api/actuator/health